### ISSUE TITLE
Tool Head Freezes when Parshing GCode 

### ISSUE THREAD

**Issue by hsojhcoom** [mtu-most/franklin#37]
When a print finishes and something its parsing the tool head freezes at the target end of last gcode in the file. It isnt a huge deal but it does make a small dent in the plastic.

**Comment by wijnen** [comment]
This problem actually became worse with the new code to parse G-Code with the c driver.  Before, it would freeze if it finished during parsing.  Now it freezes if it's printing while it's parsing.  So it shouldn't allow parsing of G-Code during a print.

On the plus side, parsing because a lot faster, so it's quite possible that it's done before the firmware buffer runs out, in which case there is no problem.

I'm keeping this open because it seems like a good idea to make it impossible to upload new files during a print.

**Comment by lmbrueck** [comment]
This doesn't seem to be a problem at all in much older versions were even very long G-Code parsing does not seem to stop the print.

Also would it be possible to either get a new image file posted for Athena or get a bit more guidance on creating these image files? I'd love to try out many of the new features and fixes you are working on but am not sure how to create the image file or update my current one.

**Comment by wijnen** [comment]
That's correct.  The reason is that there are several processes involved, which
communicate but run independently.  The important ones here are the python
driver and the c driver.  Running a print job is entirely handled by the c
driver.  In the old code, where the python driver does the parsing, it will
stop responding (so for example the temperature graph stops updating), but the
c driver has nothing to do with it and continues printing.  The only exception
is G28.  In response to that, the c driver will inform the python driver that
it should park the print head, and the python driver then sends the commands to
do that.  This is the reason it cannot do this while it's parsing G-Code.

With the new code, parsing is done by the c driver, which means that it is much
faster, but also that it will stop anything else the c driver is doing.  So
that will suspend the print job.

Building the images is quite hard, and it seems to change every time I do it.
The code I use is on github, in the account of phidiasllc, but I don't
recommend anyone to use it.

Instead, you should log into the Beaglebone with ssh and get Franklin's source
from github and run "make":

git clone https://github.com/mtu-most/franklin
cd franklin
make

This will probably abort with a message about missing dependencies.  Install
those with "sudo apt-get install packagename" (fill in the package names from
the error message).  Once it completes without errors, the new version is
installed and ready to use.

For logging in over ssh, you need to use the username "debian" and the password
"reprap".

**Comment by wijnen** [comment]
The last commit fixes this. The parsing is completely rewritten and now it cuts corners (using the max deviation setting or G64 code) so it can move faster. During this change I turned the cdriver into a Python module for better integration. While the cdriver is still a separate process (forked from the module startup code), I put the parsing code into the parent process. This restored the situation where the job keeps running while code is parsing (but the interface is still frozen).
